/* Generated by tools/fetch_photos.py. Do not edit by hand. */
window.PHOTO_CREDITS = {
 "date-palm": {
  "file": "Dates005.jpg",
  "author": "Nepenthes",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Dates005.jpg"
 },
 "sidr": {
  "file": "Ziziphus-areva-israel.jpg",
  "author": "Dov Grobgeld",
  "license": "Public domain",
  "licenseUrl": "",
  "source": "https://commons.wikimedia.org/wiki/File:Ziziphus-areva-israel.jpg"
 },
 "samur": {
  "file": "Vachellia_(ex_Acacia)_tortilis.jpg",
  "author": "Robur.q",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Vachellia_(ex_Acacia)_tortilis.jpg"
 },
 "talh": {
  "file": "Acacia_gerrardii,_loof_en_bloeiwyses,_Walter_Sisulu_NBT.jpg",
  "author": "JMK",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Acacia_gerrardii,_loof_en_bloeiwyses,_Walter_Sisulu_NBT.jpg"
 },
 "arak": {
  "file": "Peelo_10.jpg",
  "author": "Mehdi.sq",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Peelo_10.jpg"
 },
 "ghada": {
  "file": "Haloxylon_persicum.JPG",
  "author": "Abodi009",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Haloxylon_persicum.JPG"
 },
 "rimth": {
  "file": "Haloxylon_salicornicum_kz01.jpg",
  "author": "Krzysztof Ziarnek, Kenraiz",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Haloxylon_salicornicum_kz01.jpg"
 },
 "arfaj": {
  "file": "Rhanterium-epapposum-near-Jubail-SaudiArabia-15apr2009-JohnNorton.jpg",
  "author": "EcoLover",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Rhanterium-epapposum-near-Jubail-SaudiArabia-15apr2009-JohnNorton.jpg"
 },
 "athel": {
  "file": "Tamaris3.jpg",
  "author": "Anthere",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
  "source": "https://commons.wikimedia.org/wiki/File:Tamaris3.jpg"
 },
 "harmal": {
  "file": "Rhazya_stricta_kz03.jpg",
  "author": "Krzysztof Ziarnek, Kenraiz",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Rhazya_stricta_kz03.jpg"
 },
 "conocarpus": {
  "file": "Fruit_of_Conocarpus_lancifolius.jpg",
  "author": "Matthew Smith",
  "license": "Public domain",
  "licenseUrl": "",
  "source": "https://commons.wikimedia.org/wiki/File:Fruit_of_Conocarpus_lancifolius.jpg"
 },
 "neem": {
  "file": "Neem_Tree_in_Rajasthan,_India.jpg",
  "author": "TheSlumPanda",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Neem_Tree_in_Rajasthan,_India.jpg"
 },
 "washingtonia": {
  "file": "Arecales_-_Washingtonia_robusta_-_1.jpg",
  "author": "Emőke Dénes",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Arecales_-_Washingtonia_robusta_-_1.jpg"
 },
 "ficus": {
  "file": "Ficus_microcarpa_-_La_Gomera_01.jpg",
  "author": "H. Zell",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Ficus_microcarpa_-_La_Gomera_01.jpg"
 },
 "mesquite": {
  "file": "Prosopis_juliflora,_known_as_the_Velvet_Mesquite_(10078437503).jpg",
  "author": "Dick Culbert from Gibsons, B.C., Canada",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "source": "https://commons.wikimedia.org/wiki/File:Prosopis_juliflora,_known_as_the_Velvet_Mesquite_(10078437503).jpg"
 },
 "parkinsonia": {
  "file": "Parkinsonia_aculeata_flowers_3.jpg",
  "author": "Wendy Cutler from Vancouver, Canada",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "source": "https://commons.wikimedia.org/wiki/File:Parkinsonia_aculeata_flowers_3.jpg"
 },
 "bougainvillea": {
  "file": "Bugenwilla.Długo_kwitnaca_roslina.jpg",
  "author": "Zbigniew Niepokój",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Bugenwilla.D%C5%82ugo_kwitnaca_roslina.jpg"
 },
 "oleander": {
  "file": "Nerium_oleander_flowers_leaves.jpg",
  "author": "Alvesgaspar",
  "license": "CC BY 2.5",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
  "source": "https://commons.wikimedia.org/wiki/File:Nerium_oleander_flowers_leaves.jpg"
 },
 "jasmine": {
  "file": "Arabian_jasmin,_Tunisia_2010.jpg",
  "author": "Habib M'henni",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Arabian_jasmin,_Tunisia_2010.jpg"
 },
 "hibiscus": {
  "file": "Hibiscus_Brilliant.jpg",
  "author": "Andy / Andrew Fogg from near Cambridge, UK",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "source": "https://commons.wikimedia.org/wiki/File:Hibiscus_Brilliant.jpg"
 },
 "lantana": {
  "file": "LantanaFlowerLeaves.jpg",
  "author": "Alvesgaspar",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
  "source": "https://commons.wikimedia.org/wiki/File:LantanaFlowerLeaves.jpg"
 },
 "texas-sage": {
  "file": "Leucophyllum_frutescens_(Purple_Sage)_W2_IMG_1125.jpg",
  "author": "J.M.Garg",
  "license": "CC BY 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Leucophyllum_frutescens_(Purple_Sage)_W2_IMG_1125.jpg"
 },
 "desert-rose": {
  "file": "Adenium_obesum_02.JPG",
  "author": "Prenn",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Adenium_obesum_02.JPG"
 },
 "aloe-vera": {
  "file": "Aloe_vera_plant_in_a_container.jpg",
  "author": "Andikan Efiok Eduok",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Aloe_vera_plant_in_a_container.jpg"
 },
 "moringa": {
  "file": "DrumstickFlower.jpg",
  "author": "Venkatx5",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:DrumstickFlower.jpg"
 },
 "olive": {
  "file": "Olive_tree_(Olea_europaea)_branch_with_immature_olives,_Praça_João_do_Rio,_Lisbon,_Portugal_julesvernex2.jpg",
  "author": "Jules Verne Times Two",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Olive_tree_(Olea_europaea)_branch_with_immature_olives,_Pra%C3%A7a_Jo%C3%A3o_do_Rio,_Lisbon,_Portugal_julesvernex2.jpg"
 },
 "pomegranate": {
  "file": "Pomegranate_fruit_and_flower_(Punica_granatum)_–_Mediterranean_Symbol_in_Shkodër.jpg",
  "author": "Julianruizp",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:Pomegranate_fruit_and_flower_(Punica_granatum)_%E2%80%93_Mediterranean_Symbol_in_Shkod%C3%ABr.jpg"
 },
 "fig": {
  "file": "Ripe_fig_fruit_on_tree_(Ficus_Carica)_in_Southern_France.JPG",
  "author": "Stefan Thiesen",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "source": "https://commons.wikimedia.org/wiki/File:Ripe_fig_fruit_on_tree_(Ficus_Carica)_in_Southern_France.JPG"
 },
 "lemon": {
  "file": "P1030323.JPG",
  "author": "Elena Chochkova",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "source": "https://commons.wikimedia.org/wiki/File:P1030323.JPG"
 },
 "mint": {
  "file": "Minze.jpg",
  "author": "Simon Eugster --Simon 13:07, 2 July 2006 (UTC)",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
  "source": "https://commons.wikimedia.org/wiki/File:Minze.jpg"
 }
};
