/*
 * Plant data, grouped by city.
 *
 * To add a plant: add an object to a city's `plants` array. The `id` must be
 * unique and match the photo file name in /images (images/<id>.jpg) and its
 * entry in js/credits.js.
 *
 * To add a city: add a new key to CITIES with a `name`, `nameAr`, `plants`,
 * and optionally `spots` (places on the map) and `lookalikes`.
 *
 * origin:  "native" | "introduced"
 * where:   any of "desert", "streets", "gardens", "farms"
 * say:     pronunciation guide for the scientific name (stressed syllable in capitals)
 * range:   native range; countries use world-atlas names (see js/world.js), "@X" = REGIONS.X
 */
window.CITIES = {
  riyadh: {
    name: "Riyadh",
    nameAr: "الرياض",
    plants: [
      // ---------- Native (wild in Najd) ----------
      {
        id: "date-palm",
        en: "Date Palm",
        ar: "نخلة التمر",
        sci: "Phoenix dactylifera",
        origin: "native",
        where: ["farms", "streets", "gardens"],
        fact: "A single palm can give over 100 kg of dates a year, and Saudi Arabia grows more than 300 date varieties.",
        factAr: "النخلة الواحدة قد تعطي أكثر من 100 كيلو من التمر في السنة، وفي المملكة أكثر من 300 صنف من التمور.",
        say: "FEE-niks dak-ti-LIF-er-uh",
        range: { en: "Arabia, the Gulf & North Africa", ar: "جزيرة العرب والخليج وشمال أفريقيا", countries: ["@ARABIA", "Iraq", "Iran", "@NAFRICA", "@LEVANT"] }
      },
      {
        id: "sidr",
        en: "Sidr",
        ar: "سدر",
        sci: "Ziziphus spina-christi",
        origin: "native",
        where: ["desert", "gardens", "farms"],
        fact: "Bees make the famous, expensive Sidr honey from its flowers, and its crushed leaves were traditionally used to wash hair.",
        factAr: "يصنع النحل من زهره عسل السدر الشهير والغالي، وكانت أوراقه المطحونة تُستخدم قديماً لغسل الشعر.",
        say: "ZIZ-i-fus SPY-nuh KRIS-tee",
        range: { en: "Arabia, the Levant & northern Africa", ar: "جزيرة العرب والشام وشمال أفريقيا", countries: ["@ARABIA", "@LEVANT", "Iraq", "Iran", "Egypt", "Sudan", "Chad", "Niger", "Mali", "Mauritania", "Eritrea", "Ethiopia", "Djibouti", "Somalia", "Somaliland", "Kenya"] }
      },
      {
        id: "samur",
        en: "Samur Acacia",
        ar: "سمر",
        sci: "Vachellia tortilis",
        origin: "native",
        where: ["desert"],
        fact: "Its flat, umbrella-shaped crown makes it the classic desert tree. Camels eat its leaves despite the long thorns.",
        factAr: "تاجه المسطّح الذي يشبه المظلة يجعله رمز شجر الصحراء، والإبل تأكل أوراقه رغم أشواكه الطويلة.",
        say: "vuh-CHEL-ee-uh TOR-ti-lis",
        range: { en: "Africa & Arabia", ar: "أفريقيا وجزيرة العرب", countries: ["@ARABIA", "@LEVANT", "Egypt", "Sudan", "@EAFRICA", "@SAFRICA", "Senegal", "Mali", "Niger", "Chad", "Mauritania", "Algeria", "Morocco"] }
      },
      {
        id: "talh",
        en: "Talh Acacia",
        ar: "طلح",
        sci: "Vachellia gerrardii",
        origin: "native",
        where: ["desert"],
        fact: "A key shade tree of Najd's wadis and rawdahs, like Rawdat Khuraim. Look for its rough grey bark and paired white thorns.",
        factAr: "من أهم أشجار الظل في أودية نجد ورياضها مثل روضة خريم. تعرّف عليه من لحائه الرمادي الخشن وأشواكه البيضاء المزدوجة.",
        say: "vuh-CHEL-ee-uh jer-RAR-dee-eye",
        range: { en: "East & southern Africa, Arabia & the Levant", ar: "شرق وجنوب أفريقيا وجزيرة العرب والشام", countries: ["Saudi Arabia", "Yemen", "Oman", "Iraq", "@LEVANT", "Egypt", "@EAFRICA", "@SAFRICA"] }
      },
      {
        id: "arak",
        en: "Arak / Miswak",
        ar: "أراك",
        sci: "Salvadora persica",
        origin: "native",
        where: ["desert", "gardens"],
        fact: "Its twigs are the miswak, a natural toothbrush used for centuries. They contain antibacterial compounds and fluoride.",
        factAr: "أغصانه هي المسواك، فرشاة أسنان طبيعية استُخدمت لقرون، وفيها مواد مضادة للبكتيريا وفلورايد.",
        say: "sal-vuh-DOR-uh PER-si-kuh",
        range: { en: "Africa, Arabia & South Asia", ar: "أفريقيا وجزيرة العرب وجنوب آسيا", countries: ["@ARABIA", "Iraq", "Iran", "Pakistan", "India", "Egypt", "Sudan", "@EAFRICA", "Chad", "Niger", "Mali", "Mauritania", "Senegal", "Angola", "Namibia"] }
      },
      {
        id: "ghada",
        en: "Ghada",
        ar: "غضا",
        sci: "Haloxylon persicum",
        origin: "native",
        where: ["desert"],
        fact: "It grows on sand dunes and holds them in place. Its wood burns long and hot, so it was Arabia's favourite firewood, and Arabic poetry praises its embers.",
        factAr: "ينمو على الكثبان الرملية ويثبّتها. خشبه يشتعل طويلاً وبحرارة عالية، لذلك كان أفضل حطب في الجزيرة العربية، وتغنّى الشعراء بجمر الغضا.",
        say: "huh-LOK-si-lon PER-si-kum",
        range: { en: "Arabia, Iran & Central Asia", ar: "جزيرة العرب وإيران وآسيا الوسطى", countries: ["@ARABIA", "Iraq", "Iran", "Jordan", "Syria", "Israel", "Egypt", "@CASIA"] }
      },
      {
        id: "rimth",
        en: "Rimth",
        ar: "رمث",
        sci: "Haloxylon salicornicum",
        origin: "native",
        where: ["desert"],
        fact: "Camels love its salty, jointed green stems, which makes it one of the most important grazing shrubs of the Najd desert.",
        factAr: "تحب الإبل سيقانه الخضراء المالحة المفصّلة، لذلك يُعد من أهم نباتات المرعى في صحراء نجد.",
        say: "huh-LOK-si-lon sal-i-KOR-ni-kum",
        range: { en: "Arabia to Pakistan & northwest India", ar: "من جزيرة العرب إلى باكستان وشمال غرب الهند", countries: ["@ARABIA", "Iraq", "Iran", "Afghanistan", "Pakistan", "India", "Jordan", "Syria", "Egypt", "Libya"] }
      },
      {
        id: "arfaj",
        en: "Arfaj",
        ar: "عرفج",
        sci: "Rhanterium epapposum",
        origin: "native",
        where: ["desert"],
        fact: "It looks dead and grey in the dry season, then turns green with yellow flowers a few days after rain. It's Kuwait's national flower.",
        factAr: "يبدو يابساً ورمادياً في موسم الجفاف، ثم يخضرّ وتظهر أزهاره الصفراء بعد المطر بأيام. وهو الزهرة الوطنية للكويت.",
        say: "ran-TEER-ee-um ee-pap-POH-sum",
        range: { en: "Northeast Arabia & Iraq", ar: "شمال شرق جزيرة العرب والعراق", countries: ["Saudi Arabia", "Kuwait", "Qatar", "United Arab Emirates", "Iraq", "Iran"] }
      },
      {
        id: "athel",
        en: "Athel Tamarisk",
        ar: "أثل",
        sci: "Tamarix aphylla",
        origin: "native",
        where: ["farms", "desert", "streets"],
        fact: "Its needle-like leaves push out salt, so it survives salty soil. It was planted as a windbreak around farms, and its wood was used in old Najdi houses.",
        factAr: "أوراقه الإبرية تُخرج الملح، لذلك يعيش في التربة المالحة. كان يُزرع مصدّاً للرياح حول المزارع، واستُخدم خشبه في بيوت نجد القديمة.",
        say: "TAM-uh-riks uh-FIL-uh",
        range: { en: "North & East Africa to India", ar: "من شمال وشرق أفريقيا إلى الهند", countries: ["@ARABIA", "Iraq", "Iran", "Afghanistan", "Pakistan", "India", "@LEVANT", "@NAFRICA", "Sudan", "Chad", "Niger", "Mali", "Mauritania", "Ethiopia", "Eritrea", "Somalia", "Kenya"] }
      },
      {
        id: "harmal",
        en: "Harmal (Rhazya)",
        ar: "حرمل",
        sci: "Rhazya stricta",
        origin: "native",
        where: ["desert"],
        fact: "It's very bitter and toxic, so grazing animals leave it alone. That's why it forms thick green patches on heavily grazed land.",
        factAr: "طعمه مرّ جداً وهو سام، فتتجنبه المواشي. لهذا تراه يكوّن بقعاً خضراء كثيفة في الأراضي التي رعتها الماشية بكثرة.",
        say: "RAZ-ee-uh STRIK-tuh",
        range: { en: "Arabia to Pakistan & India", ar: "من جزيرة العرب إلى باكستان والهند", countries: ["@ARABIA", "Iraq", "Iran", "Afghanistan", "Pakistan", "India"] }
      },

      // ---------- Introduced (streets, parks, homes) ----------
      {
        id: "conocarpus",
        en: "Conocarpus",
        ar: "كونوكاربس",
        sci: "Conocarpus lancifolius",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "It grows fast and stays green, so Gulf cities planted it everywhere. Its aggressive roots damage pipes and foundations, so authorities now discourage planting it.",
        factAr: "ينمو بسرعة ويبقى أخضر، فزُرع بكثرة في مدن الخليج. لكن جذوره العدوانية تضر الأنابيب والأساسات، لذلك صارت الجهات المختصة لا تشجع على زراعته.",
        say: "koh-noh-KAR-pus lan-si-FOH-lee-us",
        range: { en: "Somalia & Yemen", ar: "الصومال واليمن", countries: ["Somalia", "Somaliland", "Djibouti", "Yemen"] }
      },
      {
        id: "neem",
        en: "Neem",
        ar: "نيم",
        sci: "Azadirachta indica",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "In India it's called \"the village pharmacy\". Huge neem plantations shade pilgrims at Arafat near Makkah.",
        factAr: "يسمونه في الهند \"صيدلية القرية\". وتظلّل مزارع النيم الكبيرة الحجاج في عرفات قرب مكة.",
        say: "uh-zad-i-RAK-tuh IN-di-kuh",
        range: { en: "Indian subcontinent & Myanmar", ar: "شبه القارة الهندية وميانمار", countries: ["India", "Pakistan", "Bangladesh", "Nepal", "Sri Lanka", "Myanmar"] }
      },
      {
        id: "washingtonia",
        en: "Washingtonia Palm",
        ar: "واشنطونيا",
        sci: "Washingtonia robusta",
        origin: "introduced",
        where: ["streets"],
        fact: "This tall, skinny fan palm from Mexico can reach 30 m. Unless the old fronds are trimmed, they hang down in a brown \"skirt\".",
        factAr: "نخلة مروحية طويلة ونحيلة أصلها من المكسيك، وقد يصل طولها إلى 30 متراً. إذا لم تُقصّ سعفاتها القديمة تتدلى حول الجذع مثل \"تنورة\" بنية.",
        say: "wosh-ing-TOH-nee-uh roh-BUS-tuh",
        range: { en: "Northwest Mexico", ar: "شمال غرب المكسيك", countries: ["Mexico"] }
      },
      {
        id: "ficus",
        en: "Ficus",
        ar: "فيكس",
        sci: "Ficus microcarpa",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "Locally sold as \"Ficus nitida\". Its shiny leaves take hard pruning well, so it's clipped into the thick green walls and balls you see along Riyadh villas.",
        factAr: "يُباع محلياً باسم \"فيكس نتدا\". أوراقه اللامعة تتحمل القص الشديد، لذلك تُشكّل منه الأسوار الخضراء الكثيفة والكرات التي تراها حول فلل الرياض.",
        say: "FY-kus my-kroh-KAR-puh",
        range: { en: "South & Southeast Asia to Australia", ar: "جنوب وجنوب شرق آسيا حتى أستراليا", countries: ["India", "Sri Lanka", "Bangladesh", "Myanmar", "Thailand", "Laos", "Cambodia", "Vietnam", "China", "Taiwan", "Japan", "Malaysia", "Indonesia", "Philippines", "Papua New Guinea", "Australia"] }
      },
      {
        id: "mesquite",
        en: "Mesquite",
        ar: "برسوبس",
        sci: "Prosopis juliflora",
        origin: "introduced",
        where: ["streets", "desert"],
        fact: "It was brought in to fight desertification, but it spread aggressively. Livestock eat its sweet pods and spread the seeds even further.",
        factAr: "جُلب لمكافحة التصحر لكنه انتشر بشكل كبير. تأكل المواشي قرونه الحلوة وتنشر بذوره أكثر.",
        say: "proh-SOH-pis joo-li-FLOR-uh",
        range: { en: "Mexico, Central & northern South America", ar: "المكسيك وأمريكا الوسطى وشمال أمريكا الجنوبية", countries: ["@CAMERICA", "Colombia", "Venezuela", "Ecuador", "Peru", "Cuba", "Haiti", "Dominican Rep.", "Jamaica"] }
      },
      {
        id: "parkinsonia",
        en: "Parkinsonia",
        ar: "باركنسونيا",
        sci: "Parkinsonia aculeata",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "Its green bark photosynthesises, so the tree can drop its tiny leaves in a drought and keep making food.",
        factAr: "لحاؤه الأخضر يقوم بالبناء الضوئي، فتستطيع الشجرة إسقاط أوراقها الصغيرة وقت الجفاف وتستمر في صنع غذائها.",
        say: "par-kin-SOH-nee-uh uh-kew-lee-AY-tuh",
        range: { en: "Southwest USA to Argentina", ar: "من جنوب غرب أمريكا إلى الأرجنتين", countries: ["United States of America", "@CAMERICA", "@NSAMERICA", "Bolivia", "Paraguay", "Argentina"] }
      },
      {
        id: "bougainvillea",
        en: "Bougainvillea",
        ar: "جهنمية",
        sci: "Bougainvillea glabra",
        origin: "introduced",
        where: ["gardens", "streets"],
        fact: "The bright pink \"petals\" are really bracts, a kind of papery leaf. The true flowers are the tiny white tubes in the middle.",
        factAr: "\"البتلات\" الوردية الزاهية هي في الحقيقة قنابات، أوراق رقيقة ملوّنة. أما الأزهار الحقيقية فهي الأنابيب البيضاء الصغيرة في الوسط.",
        say: "boo-gin-VIL-ee-uh GLAY-bruh",
        range: { en: "Brazil", ar: "البرازيل", countries: ["Brazil"] }
      },
      {
        id: "oleander",
        en: "Oleander",
        ar: "دفلة",
        sci: "Nerium oleander",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "It's beautiful and very drought-tolerant, but every part is highly poisonous, even the smoke from burning it.",
        factAr: "جميلة وتتحمل الجفاف كثيراً، لكن كل أجزائها شديدة السمية، حتى الدخان الناتج عن حرقها.",
        say: "NEER-ee-um oh-lee-AN-der",
        range: { en: "Mediterranean to South Asia", ar: "من البحر المتوسط إلى جنوب آسيا", countries: ["Morocco", "Algeria", "Tunisia", "Libya", "Spain", "Portugal", "France", "Italy", "Greece", "Albania", "Croatia", "Montenegro", "Turkey", "Cyprus", "N. Cyprus", "@LEVANT", "Iraq", "Iran", "Afghanistan", "Pakistan", "India", "Saudi Arabia", "Yemen", "Oman"] }
      },
      {
        id: "jasmine",
        en: "Arabian Jasmine (Fulla)",
        ar: "فل جازاني / ياسمين عربي",
        sci: "Jasminum sambac",
        origin: "introduced",
        where: ["gardens"],
        fact: "In Saudi Arabia it is called fulla jazani, after Jazan where it is grown in fields. Its small white flowers smell strongest in the evening and are strung into garlands for weddings.",
        factAr: "يسمى في السعودية الفل الجازاني نسبة إلى جازان حيث يُزرع في الحقول، ويسميه بعض الناس الياسمين العربي. أزهاره البيضاء الصغيرة أطيب ما تكون رائحتها في المساء، وتُنظم منه عقود الأعراس.",
        say: "JAZ-mi-num SAM-bak",
        range: { en: "Eastern Himalayas (India, Bhutan)", ar: "شرق الهيمالايا (الهند وبوتان)", countries: ["India", "Bhutan", "Bangladesh"] }
      },
      {
        id: "hibiscus",
        en: "Hibiscus",
        ar: "كركديه / هبسكس",
        sci: "Hibiscus rosa-sinensis",
        origin: "introduced",
        where: ["gardens"],
        fact: "Each big flower lasts only about a day. Karkadeh tea is made from a close cousin, Hibiscus sabdariffa.",
        factAr: "كل زهرة كبيرة تعيش يوماً واحداً تقريباً. أما شاي الكركديه فيُصنع من نبات قريب منه اسمه Hibiscus sabdariffa.",
        say: "hy-BIS-kus ROH-zuh si-NEN-sis",
        range: { en: "Probably southern China (an old garden hybrid)", ar: "غالباً جنوب الصين (هجين زراعي قديم)", countries: ["China", "Vietnam"] }
      },
      {
        id: "lantana",
        en: "Lantana",
        ar: "لانتانا",
        sci: "Lantana camara",
        origin: "introduced",
        where: ["gardens", "streets"],
        fact: "The flower clusters change colour as they age, so one cluster can be yellow, orange and pink at once. Butterflies love it.",
        factAr: "تتغير ألوان عناقيد أزهارها مع العمر، فقد يكون العنقود الواحد أصفر وبرتقالياً ووردياً معاً. والفراشات تحبها.",
        say: "lan-TAH-nuh kuh-MAR-uh",
        range: { en: "Central & South America", ar: "أمريكا الوسطى والجنوبية", countries: ["@CAMERICA", "@NSAMERICA", "Brazil", "Bolivia", "Paraguay", "Cuba", "Haiti", "Dominican Rep.", "Jamaica", "Puerto Rico"] }
      },
      {
        id: "texas-sage",
        en: "Texas Sage",
        ar: "ليكوفيلم",
        sci: "Leucophyllum frutescens",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "It's nicknamed the \"barometer bush\" because it covers itself in purple flowers just after rain or a humid spell.",
        factAr: "يُلقّب بـ\"شجيرة البارومتر\" لأنه يكتسي بالأزهار البنفسجية بعد المطر أو الجو الرطب مباشرة.",
        say: "loo-koh-FIL-um froo-TES-enz",
        range: { en: "Texas (USA) & northern Mexico", ar: "تكساس (أمريكا) وشمال المكسيك", countries: ["United States of America", "Mexico"] }
      },
      {
        id: "desert-rose",
        en: "Desert Rose",
        ar: "وردة الصحراء",
        sci: "Adenium obesum",
        origin: "introduced",
        where: ["gardens"],
        fact: "It stores water in its fat, swollen trunk. Its milky sap is toxic and was once used as arrow poison.",
        factAr: "تخزّن الماء في جذعها المنتفخ. عصارتها البيضاء سامة، واستُخدمت قديماً سُمّاً للسهام.",
        say: "uh-DEE-nee-um oh-BEE-sum",
        range: { en: "Africa south of the Sahara & southwest Arabia", ar: "أفريقيا جنوب الصحراء وجنوب غرب جزيرة العرب", countries: ["Saudi Arabia", "Yemen", "Oman", "Sudan", "S. Sudan", "Eritrea", "Ethiopia", "Somalia", "Somaliland", "Djibouti", "Kenya", "Uganda", "Tanzania", "Mali", "Niger", "Chad", "Nigeria", "Senegal", "Mauritania"] }
      },
      {
        id: "aloe-vera",
        en: "Aloe Vera",
        ar: "صبار الألوفيرا",
        sci: "Aloe vera",
        origin: "introduced",
        where: ["gardens"],
        fact: "The cooling gel inside its leaves soothes burns. Botanists think the plant first came from the Arabian Peninsula.",
        factAr: "الهلام البارد داخل أوراقها يلطّف الحروق، ويعتقد علماء النبات أن أصلها من شبه الجزيرة العربية.",
        say: "AL-oh VEER-uh",
        range: { en: "Arabian Peninsula (probably)", ar: "شبه الجزيرة العربية (على الأرجح)", countries: ["Oman", "Yemen", "Saudi Arabia"] }
      },
      {
        id: "moringa",
        en: "Moringa",
        ar: "مورينجا",
        sci: "Moringa oleifera",
        origin: "introduced",
        where: ["gardens", "farms"],
        fact: "It's called the \"miracle tree\": its leaves are packed with vitamins, and its crushed seeds can help clean muddy water.",
        factAr: "تُسمى \"الشجرة المعجزة\": أوراقها غنية بالفيتامينات، وبذورها المطحونة تساعد على تنقية الماء العكر.",
        say: "mor-ING-guh oh-lee-IF-er-uh",
        range: { en: "Foothills of the Himalayas (India)", ar: "سفوح الهيمالايا (الهند)", countries: ["India", "Pakistan", "Nepal", "Bangladesh"] }
      },
      {
        id: "olive",
        en: "Olive",
        ar: "زيتون",
        sci: "Olea europaea",
        origin: "introduced",
        where: ["farms", "gardens"],
        fact: "Olive trees can live for over 1,000 years. The Al-Jouf region in northern Saudi Arabia has millions of them.",
        factAr: "قد تعيش شجرة الزيتون أكثر من 1000 سنة، وفي منطقة الجوف شمال المملكة ملايين منها.",
        say: "OH-lee-uh yoo-roh-PEE-uh",
        range: { en: "Mediterranean", ar: "حوض البحر المتوسط", countries: ["Spain", "Portugal", "France", "Italy", "Greece", "Albania", "Croatia", "Montenegro", "Bosnia and Herz.", "Cyprus", "N. Cyprus", "Turkey", "@LEVANT", "Morocco", "Algeria", "Tunisia", "Libya", "Egypt"] }
      },
      {
        id: "pomegranate",
        en: "Pomegranate",
        ar: "رمان",
        sci: "Punica granatum",
        origin: "introduced",
        where: ["farms", "gardens"],
        fact: "It's mentioned in the Qur'an, and a single fruit can hold more than 600 juicy seeds.",
        factAr: "ورد ذكره في القرآن الكريم، وقد تحتوي الرمانة الواحدة على أكثر من 600 حبة.",
        say: "PEW-ni-kuh gruh-NAY-tum",
        range: { en: "Iran to northern India", ar: "من إيران إلى شمال الهند", countries: ["Iran", "Afghanistan", "Turkmenistan", "Pakistan", "India", "Iraq", "Armenia", "Azerbaijan", "Georgia"] }
      },
      {
        id: "fig",
        en: "Fig",
        ar: "تين",
        sci: "Ficus carica",
        origin: "introduced",
        where: ["farms", "gardens"],
        fact: "A fig isn't really a fruit. It's a cluster of tiny flowers turned inside-out, hidden inside a green pouch.",
        factAr: "التينة ليست ثمرة بالمعنى المعروف، بل عنقود من أزهار صغيرة مقلوبة إلى الداخل داخل كيس أخضر.",
        say: "FY-kus KAR-i-kuh",
        range: { en: "Middle East & western Asia", ar: "الشرق الأوسط وغرب آسيا", countries: ["Turkey", "@LEVANT", "Iraq", "Iran", "Afghanistan", "Armenia", "Azerbaijan", "Georgia", "Greece", "Cyprus"] }
      },
      {
        id: "lemon",
        en: "Lemon",
        ar: "ليمون",
        sci: "Citrus limon",
        origin: "introduced",
        where: ["farms", "gardens"],
        fact: "A lemon tree can flower and fruit at the same time, and it keeps producing lemons almost all year round.",
        factAr: "شجرة الليمون تزهر وتثمر في الوقت نفسه، وتعطي الليمون تقريباً طوال السنة.",
        say: "SIT-rus LY-mon",
        range: { en: "Northeast India, Myanmar & China (an ancient hybrid)", ar: "شمال شرق الهند وميانمار والصين (هجين قديم)", countries: ["India", "Myanmar", "China"] }
      },
      {
        id: "mint",
        en: "Mint",
        ar: "نعناع",
        sci: "Mentha spicata",
        origin: "introduced",
        where: ["gardens", "farms"],
        fact: "Mint tea is part of Saudi hospitality. Mint spreads fast through underground runners, so grow it in a pot.",
        factAr: "شاي النعناع جزء من الضيافة السعودية. ينتشر النعناع بسرعة عبر سيقان تحت التربة، لذلك ازرعه في أصيص.",
        say: "MEN-thuh spy-KAY-tuh",
        range: { en: "Europe & western Asia", ar: "أوروبا وغرب آسيا", countries: ["Spain", "Portugal", "France", "Italy", "Greece", "Germany", "Austria", "Switzerland", "Hungary", "Romania", "Bulgaria", "Serbia", "Croatia", "Poland", "Czechia", "Slovakia", "Ukraine", "Turkey", "@LEVANT", "Iraq", "Iran", "Georgia", "Armenia", "Azerbaijan"] }
      },

      // ---------- Added: 30 more Riyadh plants ----------
      {
        id: "awsaj",
        en: "Awsaj (Desert Thorn)",
        ar: "عوسج",
        sci: "Lycium shawii",
        origin: "native",
        where: ["desert"],
        fact: "A spiny shrub with tiny leaves and small red berries that birds love. Bedouins used it for thorn fences to protect their animals at night.",
        factAr: "شجيرة شوكية أوراقها صغيرة وثمارها حمراء صغيرة تحبها الطيور. كان البدو يستخدمونها لعمل سياج شوكي يحمي مواشيهم في الليل.",
        say: "LY-see-um SHAW-ee-eye",
        range: { en: "Arabia, the Levant, NE Africa & Iran to India", ar: "جزيرة العرب والشام وشمال شرق أفريقيا ومن إيران إلى الهند", countries: ["@ARABIA", "@LEVANT", "Iraq", "Iran", "Pakistan", "India", "Egypt", "Sudan", "Eritrea", "Ethiopia", "Somalia", "Somaliland", "Kenya"] }
      },
      {
        id: "markh",
        en: "Markh (Broom Bush)",
        ar: "مرخ",
        sci: "Leptadenia pyrotechnica",
        origin: "native",
        where: ["desert"],
        fact: "Its bundles of leafless green stems look like a broom. Arabs used its dry twigs to start fires by friction, and an old Arabic proverb says every tree holds fire, but markh holds the most.",
        factAr: "سيقانه الخضراء الخالية من الأوراق تشبه المكنسة. استخدم العرب أعواده الجافة لإشعال النار بالاحتكاك، ومنه المثل: «في كل شجر نار، واستمجد المرخ والعفار».",
        say: "lep-tuh-DEE-nee-uh py-roh-TEK-ni-kuh",
        range: { en: "Sahara, Arabia & NW India", ar: "الصحراء الكبرى وجزيرة العرب وشمال غرب الهند", countries: ["@ARABIA", "Iraq", "Iran", "Pakistan", "India", "Egypt", "Sudan", "Chad", "Niger", "Mali", "Mauritania", "Senegal", "Libya", "Algeria", "Eritrea", "Ethiopia", "Somalia"] }
      },
      {
        id: "arta",
        en: "Arta",
        ar: "أرطى",
        sci: "Calligonum comosum",
        origin: "native",
        where: ["desert"],
        fact: "A sand-dune shrub with jointed green twigs and fluffy, bristly fruit. Its roots bind the sand, and its bark was once used to tan leather.",
        factAr: "شجيرة تنمو في الكثبان الرملية، سيقانها خضراء مفصّلة وثمارها منفوشة كثيرة الشعيرات. جذورها تثبت الرمل، وكان لحاؤها يُستخدم قديماً في دباغة الجلود.",
        say: "kal-li-GOH-num koh-MOH-sum",
        range: { en: "North Africa, Arabia & Iran to Pakistan", ar: "شمال أفريقيا وجزيرة العرب ومن إيران إلى باكستان", countries: ["@ARABIA", "Iraq", "Iran", "Afghanistan", "Pakistan", "Jordan", "Syria", "Israel", "Egypt", "Libya", "Tunisia", "Algeria", "Morocco"] }
      },
      {
        id: "ushar",
        en: "Ushar (Sodom Apple)",
        ar: "عشار",
        sci: "Calotropis procera",
        origin: "native",
        where: ["desert", "streets"],
        fact: "It grows on roadsides and empty lots all over Riyadh. Its big green fruit is hollow like a balloon, and its milky sap is poisonous and burns the eyes.",
        factAr: "ينتشر على جوانب الطرق والأراضي الفضاء في كل الرياض. ثمرته الخضراء الكبيرة مجوّفة مثل البالون، وعصارته البيضاء سامة وتؤذي العين.",
        say: "kal-oh-TROH-pis PROH-ser-uh",
        range: { en: "Africa, Arabia & South Asia", ar: "أفريقيا وجزيرة العرب وجنوب آسيا", countries: ["@ARABIA", "@LEVANT", "Iraq", "Iran", "Afghanistan", "Pakistan", "India", "@NAFRICA", "@EAFRICA", "Chad", "Niger", "Mali", "Mauritania", "Senegal", "Nigeria"] }
      },
      {
        id: "hanzal",
        en: "Hanzal (Bitter Apple)",
        ar: "حنظل",
        sci: "Citrullus colocynthis",
        origin: "native",
        where: ["desert"],
        fact: "A creeping vine with round, striped fruit that looks like a small watermelon but is extremely bitter. \"Bitter as hanzal\" is a common Arabic saying.",
        factAr: "نبات زاحف ثمرته كروية مخططة تشبه البطيخ الصغير لكنها شديدة المرارة. ويقال في العربية: «أمرّ من الحنظل».",
        say: "si-TRUL-us kol-oh-SIN-this",
        range: { en: "Sahara, Arabia & SW Asia", ar: "الصحراء الكبرى وجزيرة العرب وجنوب غرب آسيا", countries: ["@ARABIA", "@LEVANT", "Iraq", "Iran", "Afghanistan", "Pakistan", "India", "@NAFRICA", "Sudan", "Chad", "Niger", "Mali", "Mauritania"] }
      },
      {
        id: "nussi",
        en: "Nussi (Silky Grass)",
        ar: "نصي",
        sci: "Stipagrostis plumosa",
        origin: "native",
        where: ["desert"],
        fact: "One of the best desert grasses for grazing. Its feathery seed heads shine silver in the wind, and it turns green quickly after rain.",
        factAr: "من أفضل أعشاب المرعى في الصحراء. سنابله الريشية تلمع بلون فضي مع الريح، ويخضرّ بسرعة بعد المطر.",
        say: "sti-puh-GROS-tis ploo-MOH-suh",
        range: { en: "North Africa to Central Asia", ar: "من شمال أفريقيا إلى آسيا الوسطى", countries: ["@ARABIA", "@LEVANT", "Iraq", "Iran", "Afghanistan", "Pakistan", "@CASIA", "@NAFRICA"] }
      },
      {
        id: "thumam",
        en: "Thumam",
        ar: "ثمام",
        sci: "Panicum turgidum",
        origin: "native",
        where: ["desert"],
        fact: "A tough, bamboo-like grass that forms big clumps on sand. It was used to thatch roofs and stuff pillows, and the thumam of Arabic poetry is this grass.",
        factAr: "عشب قوي يشبه الخيزران ويكوّن تجمعات كبيرة على الرمل. كان يُستخدم في تسقيف البيوت وحشو الوسائد، وهو الثمام الذي ورد في الشعر العربي.",
        say: "PAN-i-kum TUR-ji-dum",
        range: { en: "Sahara, the Sahel, Arabia & Pakistan", ar: "الصحراء الكبرى والساحل وجزيرة العرب وباكستان", countries: ["@ARABIA", "Iraq", "Iran", "Pakistan", "@NAFRICA", "Sudan", "Chad", "Niger", "Mali", "Mauritania", "Senegal", "Eritrea", "Ethiopia", "Somalia"] }
      },
      {
        id: "kaff",
        en: "Kaff Maryam (Rose of Jericho)",
        ar: "كف مريم الصحراوي",
        sci: "Anastatica hierochuntica",
        origin: "native",
        where: ["desert"],
        fact: "When it dries, it curls up into a tight wooden ball. Drop it in water and it opens like a hand, which is why it's called \"Mary's palm\".",
        factAr: "عندما يجف يلتف على نفسه مثل كرة خشبية مقفلة، وإذا وُضع في الماء انفتح مثل الكف، ولذلك سُمي «كف مريم».",
        say: "an-uh-STAT-i-kuh hy-er-oh-KUN-ti-kuh",
        range: { en: "Sahara, Arabia & Iran to Pakistan", ar: "الصحراء الكبرى وجزيرة العرب ومن إيران إلى باكستان", countries: ["@ARABIA", "Jordan", "Israel", "Iraq", "Iran", "Pakistan", "@NAFRICA", "Sudan", "Chad", "Niger", "Mali", "Mauritania"] }
      },
      {
        id: "shih",
        en: "Shih (Desert Wormwood)",
        ar: "شيح",
        sci: "Artemisia herba-alba",
        origin: "native",
        where: ["desert"],
        fact: "A small silvery shrub with a strong, bitter-sweet smell. Rub a leaf and you will know it. It's used in folk medicine and to scent the desert air after rain.",
        factAr: "شجيرة صغيرة فضية اللون ذات رائحة قوية مرّة حلوة، إذا فركت ورقة منها عرفتها. تُستخدم في الطب الشعبي، وتعطر هواء البر بعد المطر.",
        say: "ar-te-MIZ-ee-uh HER-buh AL-buh",
        range: { en: "Arabia, the Levant, Iran & Central Asia", ar: "جزيرة العرب والشام وإيران وآسيا الوسطى", countries: ["@ARABIA", "@LEVANT", "Iraq", "Iran", "Afghanistan", "@CASIA", "Egypt"] }
      },
      {
        id: "qaysoom",
        en: "Qaysoom",
        ar: "قيصوم",
        sci: "Achillea fragrantissima",
        origin: "native",
        where: ["desert"],
        fact: "A grey, woolly shrub with button-like yellow flowers and a strong camphor smell. It is a classic herb of the Arabian desert, often mentioned together with shih.",
        factAr: "شجيرة رمادية صوفية أزهارها صفراء تشبه الأزرار ورائحتها قوية تشبه الكافور. من أعشاب صحراء العرب المعروفة، وكثيراً ما يُذكر مع الشيح.",
        say: "a-KIL-ee-uh fray-gran-TIS-i-muh",
        range: { en: "Arabia, Sinai, the Levant, Iraq & Iran", ar: "جزيرة العرب وسيناء والشام والعراق وإيران", countries: ["Saudi Arabia", "Kuwait", "Iraq", "Iran", "@LEVANT", "Egypt"] }
      },
      {
        id: "salam",
        en: "Salam Acacia",
        ar: "سلم",
        sci: "Vachellia flava",
        origin: "native",
        where: ["desert"],
        fact: "A small, bushy acacia with yellow ball flowers and pairs of straight white thorns. It is an important browse tree for camels.",
        factAr: "شجرة أكاسيا صغيرة كثيفة أزهارها صفراء كروية وأشواكها بيضاء مستقيمة مزدوجة. تُعد من أشجار المرعى المهمة للإبل.",
        say: "vuh-CHEL-ee-uh FLAY-vuh",
        range: { en: "Sahara, Sahel, NE Africa & Arabia", ar: "الصحراء الكبرى والساحل وشمال شرق أفريقيا وجزيرة العرب", countries: ["@ARABIA", "Jordan", "Israel", "Egypt", "Libya", "Algeria", "Sudan", "Chad", "Niger", "Mali", "Mauritania", "Eritrea", "Ethiopia", "Somalia", "Kenya"] }
      },
      {
        id: "sarh",
        en: "Sarh",
        ar: "سرح",
        sci: "Maerua crassifolia",
        origin: "native",
        where: ["desert"],
        fact: "An evergreen desert tree with small, thick leaves that stays green in the hottest summer. Camels and goats browse it when little else is left.",
        factAr: "شجرة صحراوية دائمة الخضرة أوراقها صغيرة وسميكة، تبقى خضراء في أشد أيام الصيف حرارة. ترعاها الإبل والماعز حين يقل المرعى.",
        say: "MY-roo-uh kras-i-FOH-lee-uh",
        range: { en: "Sahara, Sahel & Arabia", ar: "الصحراء الكبرى والساحل وجزيرة العرب", countries: ["@ARABIA", "Jordan", "Israel", "Egypt", "Libya", "Algeria", "Sudan", "Chad", "Niger", "Mali", "Mauritania", "Eritrea", "Ethiopia", "Somalia", "Kenya"] }
      },
      {
        id: "dhanoon",
        en: "Dhanoon (Desert Hyacinth)",
        ar: "ذانون",
        sci: "Cistanche tubulosa",
        origin: "native",
        where: ["desert"],
        fact: "It has no green leaves at all: it's a parasite that feeds on the roots of other shrubs. In spring it pushes up a tall spike of bright yellow flowers from the sand.",
        factAr: "ليس له أوراق خضراء أبداً، فهو نبات متطفل يتغذى على جذور الشجيرات الأخرى. في الربيع يخرج من الرمل سنبلة طويلة من الأزهار الصفراء الزاهية.",
        say: "sis-TAN-kee too-bew-LOH-suh",
        range: { en: "North Africa, Arabia & Iran to China", ar: "شمال أفريقيا وجزيرة العرب ومن إيران إلى الصين", countries: ["@ARABIA", "@LEVANT", "Iraq", "Iran", "Afghanistan", "Pakistan", "India", "China", "Mongolia", "@CASIA", "Egypt", "Libya", "Algeria"] }
      },
      {
        id: "humaidh",
        en: "Humaidh (Bladder Dock)",
        ar: "حميض",
        sci: "Rumex vesicarius",
        origin: "native",
        where: ["desert"],
        fact: "A juicy spring herb with a sour, lemony taste. Its papery pink-red fruits look like tiny lanterns, and people in Najd pick its leaves to eat fresh.",
        factAr: "عشب ربيعي عصاري طعمه حامض مثل الليمون. ثماره الورقية الوردية الحمراء تشبه الفوانيس الصغيرة، ويقطف أهل نجد أوراقه ليأكلوها طازجة.",
        say: "ROO-meks ves-i-KAIR-ee-us",
        range: { en: "North Africa, Arabia & SW Asia to India", ar: "شمال أفريقيا وجزيرة العرب ومن جنوب غرب آسيا إلى الهند", countries: ["@ARABIA", "@LEVANT", "Iraq", "Iran", "Afghanistan", "Pakistan", "India", "@NAFRICA", "Sudan", "Chad", "Niger", "Ethiopia"] }
      },
      {
        id: "sadan",
        en: "Sa'dan",
        ar: "سعدان",
        sci: "Neurada procumbens",
        origin: "native",
        where: ["desert"],
        fact: "A flat, woolly plant that hugs the sand, with round spiny fruits. Camels love it, and Arabs say \"مرعى ولا كالسعدان\": good pasture, but none like sa'dan.",
        factAr: "نبات مفترش صوفي يلتصق بالرمل، ثماره مستديرة شوكية. تحبه الإبل كثيراً، ومن أمثال العرب: «مرعى ولا كالسعدان».",
        say: "new-RAY-duh proh-KUM-benz",
        range: { en: "Sahara, Arabia & NW India", ar: "الصحراء الكبرى وجزيرة العرب وشمال غرب الهند", countries: ["@ARABIA", "@LEVANT", "Iraq", "Iran", "Pakistan", "India", "@NAFRICA", "Sudan", "Chad", "Niger", "Mali", "Mauritania"] }
      },
      {
        id: "albizia",
        en: "Albizia (Lebbek)",
        ar: "لبخ",
        sci: "Albizia lebbeck",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "A big shade tree with fluffy, scented flower balls. Its long, papery pods rattle in the wind, which is why it's called \"woman's tongue\" in English.",
        factAr: "شجرة ظل كبيرة أزهارها كرات منفوشة عطرة. قرونها الطويلة الورقية تُخشخش مع الريح، ولذلك تُسمى بالإنجليزية «لسان المرأة».",
        say: "al-BIZ-ee-uh LEB-ek",
        range: { en: "South & Southeast Asia to northern Australia", ar: "جنوب وجنوب شرق آسيا حتى شمال أستراليا", countries: ["India", "Pakistan", "Bangladesh", "Nepal", "Sri Lanka", "Myanmar", "Thailand", "Laos", "Cambodia", "Vietnam", "Malaysia", "Indonesia", "Papua New Guinea", "Australia"] }
      },
      {
        id: "tecoma",
        en: "Yellow Bells (Tecoma)",
        ar: "تيكوما",
        sci: "Tecoma stans",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "A fast-growing shrub covered in bright yellow trumpet flowers for most of the year. It loves Riyadh's heat and is planted along many roads.",
        factAr: "شجيرة سريعة النمو تكتسي بأزهار صفراء زاهية على شكل بوق معظم أيام السنة. تحب حرارة الرياض وتُزرع على كثير من الطرق.",
        say: "teh-KOH-muh STANZ",
        range: { en: "Southern USA to Argentina", ar: "من جنوب أمريكا إلى الأرجنتين", countries: ["United States of America", "@CAMERICA", "@NSAMERICA", "Bolivia", "Argentina", "Cuba", "Haiti", "Dominican Rep.", "Jamaica"] }
      },
      {
        id: "dodonaea",
        en: "Dodonaea (Hop Bush)",
        ar: "دودونيا",
        sci: "Dodonaea viscosa",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "Its leaves are sticky and shiny, and its papery winged seed pods turn pink-red. It grows wild in the mountains of southwest Saudi Arabia and is planted as a hedge in Riyadh.",
        factAr: "أوراقها لزجة لامعة، وثمارها المجنحة الورقية يتحول لونها إلى الوردي والأحمر. تنمو برياً في جبال جنوب غرب المملكة، وتُزرع سياجاً في الرياض.",
        say: "doh-doh-NEE-uh vis-KOH-suh",
        range: { en: "Warm regions worldwide, incl. SW Arabia", ar: "المناطق الدافئة حول العالم ومنها جنوب غرب جزيرة العرب", countries: ["Yemen", "Oman", "Saudi Arabia", "Ethiopia", "Kenya", "Tanzania", "South Africa", "India", "Australia", "Mexico", "Brazil", "Peru"] }
      },
      {
        id: "casuarina",
        en: "Casuarina",
        ar: "كازورينا",
        sci: "Casuarina equisetifolia",
        origin: "introduced",
        where: ["streets", "farms"],
        fact: "It looks like a pine, but its \"needles\" are really thin green twigs with tiny leaves. It was planted as windbreaks around farms and along highways.",
        factAr: "تشبه شجرة الصنوبر، لكن «إبرها» في الحقيقة أغصان خضراء رفيعة عليها أوراق صغيرة جداً. زُرعت مصدات للرياح حول المزارع وعلى الطرق السريعة.",
        say: "kas-ew-uh-RY-nuh ek-wi-see-ti-FOH-lee-uh",
        range: { en: "Southeast Asia, Australia & Pacific", ar: "جنوب شرق آسيا وأستراليا والمحيط الهادئ", countries: ["Myanmar", "Thailand", "Vietnam", "Malaysia", "Indonesia", "Philippines", "Papua New Guinea", "Australia", "Fiji", "Vanuatu", "Solomon Is.", "New Caledonia"] }
      },
      {
        id: "eucalyptus",
        en: "Eucalyptus",
        ar: "كافور",
        sci: "Eucalyptus camaldulensis",
        origin: "introduced",
        where: ["streets", "farms"],
        fact: "An Australian tree with peeling, patchy white bark and long, hanging leaves. Crush a leaf and it smells like cough medicine.",
        factAr: "شجرة أسترالية لحاؤها يتقشر بقعاً بيضاء، وأوراقها طويلة متدلية. إذا فركت ورقة منها شممت رائحة مثل دواء الكحة.",
        say: "yoo-kuh-LIP-tus kuh-mal-doo-LEN-sis",
        range: { en: "Australia", ar: "أستراليا", countries: ["Australia"] }
      },
      {
        id: "clerodendrum",
        en: "Clerodendrum",
        ar: "كلروديندرم",
        sci: "Clerodendrum inerme",
        origin: "introduced",
        where: ["streets", "gardens"],
        fact: "A glossy green hedge seen along villa walls and parks. Its small white flowers have long purple stamens like whiskers.",
        factAr: "سياج أخضر لامع تراه على أسوار الفلل وفي الحدائق. أزهاره بيضاء صغيرة لها أسدية بنفسجية طويلة مثل الشوارب.",
        say: "kler-oh-DEN-drum in-ER-mee",
        range: { en: "Coasts of South & Southeast Asia to Australia", ar: "سواحل جنوب وجنوب شرق آسيا حتى أستراليا", countries: ["India", "Sri Lanka", "Bangladesh", "Myanmar", "Thailand", "Vietnam", "Malaysia", "Indonesia", "Philippines", "Papua New Guinea", "Australia"] }
      },
      {
        id: "duranta",
        en: "Duranta",
        ar: "دورانتا",
        sci: "Duranta erecta",
        origin: "introduced",
        where: ["gardens", "streets"],
        fact: "It has hanging clusters of small violet flowers followed by golden berries, so it's also called \"golden dewdrop\". The berries are poisonous to people.",
        factAr: "لها عناقيد متدلية من الأزهار البنفسجية الصغيرة، ثم تتبعها ثمار ذهبية، لذلك تُسمى «قطرات الندى الذهبية». الثمار سامة للإنسان.",
        say: "dew-RAN-tuh ee-REK-tuh",
        range: { en: "Mexico, Caribbean & South America", ar: "المكسيك والكاريبي وأمريكا الجنوبية", countries: ["@CAMERICA", "@NSAMERICA", "Brazil", "Bolivia", "Paraguay", "Argentina", "Cuba", "Haiti", "Dominican Rep.", "Jamaica", "Puerto Rico"] }
      },
      {
        id: "periwinkle",
        en: "Madagascar Periwinkle",
        ar: "بفتة / ونكة",
        sci: "Catharanthus roseus",
        origin: "introduced",
        where: ["gardens", "streets"],
        fact: "The pink and white bedding flower you see in Riyadh's roundabouts. It's tough in the heat, and cancer medicines have been made from it.",
        factAr: "تُعرف في السعودية باسم البفتة، وهي زهرة الأحواض الوردية والبيضاء التي تراها في دوارات الرياض. تتحمل الحر، وصُنعت منها أدوية لعلاج السرطان.",
        say: "kath-uh-RAN-thus ROH-zee-us",
        range: { en: "Madagascar", ar: "مدغشقر", countries: ["Madagascar"] }
      },
      {
        id: "basil",
        en: "Italian Basil",
        ar: "ريحان إيطالي",
        sci: "Ocimum basilicum",
        origin: "introduced",
        where: ["gardens", "farms"],
        fact: "A sweet-smelling herb grown in pots and home gardens. Rayhan is mentioned in the Qur'an as one of the delights of paradise.",
        factAr: "عشب عطري يُزرع في الأصص وحدائق البيوت. وورد ذكر الريحان في القرآن الكريم من نعيم الجنة.",
        say: "OSS-i-mum buh-SIL-i-kum",
        range: { en: "Tropical Asia & Africa", ar: "المناطق الاستوائية في آسيا وأفريقيا", countries: ["India", "Sri Lanka", "Bangladesh", "Myanmar", "Thailand", "Pakistan", "Iran", "Ethiopia", "Kenya", "Tanzania"] }
      },
      {
        id: "henna",
        en: "Henna",
        ar: "حناء",
        sci: "Lawsonia inermis",
        origin: "introduced",
        where: ["gardens", "farms"],
        fact: "The dried, crushed leaves make the orange-red dye used on hands for Eid and weddings. The small white flowers smell sweet at night.",
        factAr: "أوراقها المجففة المطحونة تعطي الصبغة الحمراء البرتقالية التي تُنقش بها الأيدي في العيد والأعراس. وأزهارها البيضاء الصغيرة طيبة الرائحة في الليل.",
        say: "law-SOH-nee-uh in-ER-mis",
        range: { en: "North & East Africa, Arabia & South Asia", ar: "شمال وشرق أفريقيا وجزيرة العرب وجنوب آسيا", countries: ["Egypt", "Sudan", "Libya", "Ethiopia", "Eritrea", "Somalia", "Kenya", "Yemen", "Oman", "Iran", "Pakistan", "India"] }
      },
      {
        id: "grape",
        en: "Grapevine",
        ar: "عنب",
        sci: "Vitis vinifera",
        origin: "introduced",
        where: ["gardens", "farms"],
        fact: "A climbing vine grown over the pergolas of old Riyadh houses for shade and fruit. It holds on with curly tendrils.",
        factAr: "نبات متسلق يُزرع على عرائش البيوت القديمة في الرياض للظل والثمر. يتشبث بمحاليق ملتفة.",
        say: "VY-tis vi-NIF-er-uh",
        range: { en: "Caucasus, Mediterranean & SW Asia", ar: "القوقاز والبحر المتوسط وجنوب غرب آسيا", countries: ["Georgia", "Armenia", "Azerbaijan", "Turkey", "Iran", "Iraq", "Syria", "Lebanon", "Greece", "Italy", "Spain", "France"] }
      },
      {
        id: "mulberry",
        en: "White Mulberry",
        ar: "توت",
        sci: "Morus alba",
        origin: "introduced",
        where: ["gardens", "farms"],
        fact: "A shady tree whose sweet fruit ripens in spring, white, pink or dark purple. Its leaves are the only food of silkworms.",
        factAr: "شجرة ظليلة تنضج ثمارها الحلوة في الربيع بألوان بيضاء أو وردية أو بنفسجية داكنة. أوراقها هي الغذاء الوحيد لدودة القز.",
        say: "MOR-us AL-buh",
        range: { en: "Northern China", ar: "شمال الصين", countries: ["China"] }
      },
      {
        id: "guava",
        en: "Guava",
        ar: "جوافة",
        sci: "Psidium guajava",
        origin: "introduced",
        where: ["gardens", "farms"],
        fact: "It has smooth, peeling copper-coloured bark and fragrant fruit that is rich in vitamin C, more than an orange.",
        factAr: "لحاؤها أملس بلون نحاسي يتقشر، وثمارها عطرية غنية بفيتامين C، أكثر من البرتقال.",
        say: "SID-ee-um gwah-HAH-vuh",
        range: { en: "Mexico, Central & South America", ar: "المكسيك وأمريكا الوسطى والجنوبية", countries: ["@CAMERICA", "@NSAMERICA", "Brazil", "Bolivia", "Paraguay"] }
      },
      {
        id: "thayyil",
        en: "Bermuda Grass",
        ar: "ثيل",
        sci: "Cynodon dactylon",
        origin: "introduced",
        where: ["gardens", "streets"],
        fact: "The fine green lawn grass of Riyadh's parks, stadiums and villas. It spreads by runners and survives the summer heat, but it needs a lot of water.",
        factAr: "عشب المسطحات الخضراء في حدائق الرياض وملاعبها وفللها. ينتشر عبر سيقان زاحفة ويتحمل حر الصيف، لكنه يحتاج كثيراً من الماء.",
        say: "SY-noh-don DAK-ti-lon",
        range: { en: "Africa & southern Asia", ar: "أفريقيا وجنوب آسيا", countries: ["@EAFRICA", "@SAFRICA", "@NAFRICA", "@ARABIA", "Iraq", "Iran", "Pakistan", "India", "Bangladesh"] }
      },
      {
        id: "alfalfa",
        en: "Alfalfa",
        ar: "برسيم",
        sci: "Medicago sativa",
        origin: "introduced",
        where: ["farms"],
        fact: "The green fodder crop grown under the big round pivot fields you see from the air around Riyadh. It feeds camels, sheep and dairy cows.",
        factAr: "محصول علف أخضر يُزرع في الدوائر الزراعية الكبيرة التي تراها من الطائرة حول الرياض. يُطعم للإبل والأغنام وأبقار الحليب.",
        say: "med-i-KAY-goh sa-TY-vuh",
        range: { en: "Iran, the Caucasus & Central Asia", ar: "إيران والقوقاز وآسيا الوسطى", countries: ["Iran", "Turkey", "Armenia", "Azerbaijan", "Georgia", "Afghanistan", "@CASIA"] }
      },

      // ---------- More garden plants (jasmines, kaff maryam tree, sitt al-hasan) ----------
      {
        id: "plumeria",
        en: "Indian Jasmine (Frangipani)",
        ar: "ياسمين هندي",
        sci: "Plumeria obtusa",
        origin: "introduced",
        where: ["gardens", "streets"],
        fact: "A small tree with thick branches, big oval leaves and large white flowers with a yellow centre and a sweet smell. Break a leaf or twig and white milky sap comes out, which irritates skin, so wash your hands.",
        factAr: "شجرة صغيرة أغصانها سميكة وأوراقها بيضاوية كبيرة، وأزهارها بيضاء كبيرة وسطها أصفر ورائحتها حلوة. إذا كسرت ورقة أو غصناً يخرج منه حليب أبيض يهيّج الجلد، فاغسل يديك.",
        say: "ploo-MEER-ee-uh ob-TOO-suh",
        range: { en: "Caribbean & Central America", ar: "الكاريبي وأمريكا الوسطى", countries: ["Cuba", "Haiti", "Dominican Rep.", "Jamaica", "Puerto Rico", "Bahamas", "Mexico", "Belize", "Guatemala", "Honduras"] }
      },
      {
        id: "rangoon",
        en: "Red Climbing Jasmine (Rangoon Creeper)",
        ar: "ياسمين أحمر متسلق",
        sci: "Combretum indicum",
        origin: "introduced",
        where: ["gardens"],
        fact: "A climbing vine grown over walls and pergolas. Its hanging flower clusters open white, turn pink, then deep red, all on the same plant, and smell very sweet, especially at night. Some people call it red Indian jasmine.",
        factAr: "نبات متسلق يُزرع على الأسوار والعرائش. عناقيد أزهاره المتدلية تتفتح بيضاء ثم تصير وردية ثم حمراء داكنة، كلها على النبتة نفسها، ورائحتها حلوة جداً خاصة في الليل. ويسميه بعض الناس الياسمين الهندي الأحمر المتسلق.",
        say: "kom-BREE-tum IN-di-kum",
        range: { en: "South & Southeast Asia", ar: "جنوب وجنوب شرق آسيا", countries: ["India", "Bangladesh", "Myanmar", "Thailand", "Laos", "Cambodia", "Vietnam", "Malaysia", "Indonesia", "Philippines", "China"] }
      },
      {
        id: "plumbago",
        en: "Blue Jasmine (Plumbago)",
        ar: "ياسمين أزرق",
        sci: "Plumbago auriculata",
        origin: "introduced",
        where: ["gardens", "streets"],
        fact: "A spreading shrub covered in clusters of sky-blue flowers for most of the year. It looks like jasmine but isn't related, and it has no scent. Its sticky seed pods cling to clothes.",
        factAr: "شجيرة منتشرة تكتسي بعناقيد من الأزهار الزرقاء السماوية معظم أيام السنة. تشبه الياسمين في شكل الزهرة لكنها ليست من فصيلته وليس لها رائحة. وقرون بذورها لزجة تلتصق بالملابس.",
        say: "plum-BAY-goh aw-rik-ew-LAY-tuh",
        range: { en: "South Africa", ar: "جنوب أفريقيا", countries: ["South Africa", "eSwatini", "Lesotho", "Mozambique"] }
      },
      {
        id: "vitex",
        en: "Kaff Maryam Tree (Chaste Tree)",
        ar: "كف مريم / شجرة العفة",
        sci: "Vitex agnus-castus",
        origin: "introduced",
        where: ["gardens", "streets"],
        fact: "A large shrub or small tree with hand-shaped leaves of 5–7 fingers, which is why it's called \"Mary's palm\". Its purple flower spikes bloom for most of the warm months and attract bees.",
        factAr: "شجيرة كبيرة أو شجرة صغيرة أوراقها مقسّمة مثل الكف إلى 5 أو 7 أصابع، ولذلك تسمى «كف مريم». سنابل أزهارها البنفسجية تتفتح معظم الأشهر الدافئة وتجذب النحل.",
        say: "VY-teks AG-nus KAS-tus",
        range: { en: "Mediterranean to Central Asia", ar: "من البحر المتوسط إلى آسيا الوسطى", countries: ["Spain", "Portugal", "France", "Italy", "Greece", "Albania", "Croatia", "Turkey", "Cyprus", "@LEVANT", "Iraq", "Iran", "Afghanistan", "@CASIA", "Morocco", "Algeria", "Tunisia", "Libya", "Egypt"] }
      },
      {
        id: "ipomoea",
        en: "Morning Glory",
        ar: "ست الحسن",
        sci: "Ipomoea purpurea",
        origin: "introduced",
        where: ["gardens"],
        fact: "A fast climbing vine with heart-shaped leaves and trumpet flowers in purple, blue or pink. Each flower opens in the morning and closes by afternoon. Its seeds are poisonous.",
        factAr: "نبات متسلق سريع النمو أوراقه على شكل قلب، وأزهاره على شكل بوق بلون بنفسجي أو أزرق أو وردي. كل زهرة تتفتح في الصباح وتنغلق بعد الظهر. بذوره سامة.",
        say: "ip-oh-MEE-uh pur-PEW-ree-uh",
        range: { en: "Mexico & Central America", ar: "المكسيك وأمريكا الوسطى", countries: ["@CAMERICA"] }
      },
      {
        id: "shamoum",
        en: "Shamoum (Local Basil)",
        ar: "شموم / ريحان بلدي",
        sci: "Ocimum basilicum (local type)",
        origin: "introduced",
        where: ["gardens", "farms"],
        fact: "The Saudi local basil. It grows tall purple flower spikes (shamarikh) and has a much stronger scent than Italian basil. People keep it in pots by the door and put a sprig in tea or by the bed for its smell.",
        factAr: "الريحان البلدي السعودي. يطلع شماريخ زهرية بنفسجية طويلة، ورائحته أقوى بكثير من الريحان الإيطالي. يُزرع في أصص عند الأبواب، ويوضع منه غصن في الشاي أو قرب السرير لرائحته.",
        say: "OSS-i-mum buh-SIL-i-kum",
        range: { en: "Tropical Asia & Africa", ar: "المناطق الاستوائية في آسيا وأفريقيا", countries: ["India", "Sri Lanka", "Bangladesh", "Myanmar", "Thailand", "Pakistan", "Iran", "Ethiopia", "Kenya", "Tanzania"] }
      }
    ],

    // Places around Riyadh where each plant is commonly seen.
    // Pins mark an area, not an exact tree. [lat, lng]
    spots: [
      { id: "wadi-hanifa", en: "Wadi Hanifa", ar: "وادي حنيفة", at: [24.648, 46.61],
        plants: ["date-palm", "athel", "sidr", "talh", "samur", "arak", "awsaj", "ushar", "markh", "casuarina", "eucalyptus"] },
      { id: "diriyah", en: "Diriyah (At-Turaif & Al-Bujairi)", ar: "الدرعية (الطريف والبجيري)", at: [24.734, 46.574],
        plants: ["date-palm", "athel", "lemon", "pomegranate", "fig", "grape", "mulberry", "henna"] },
      { id: "salam-park", en: "Al-Salam Park", ar: "منتزه السلام", at: [24.6237, 46.7069],
        plants: ["date-palm", "washingtonia", "ficus", "neem", "bougainvillea", "oleander", "lantana", "albizia", "tecoma", "thayyil", "periwinkle", "eucalyptus", "plumbago", "plumeria", "vitex"] },
      { id: "king-abdullah-park", en: "King Abdullah Park (Al-Malaz)", ar: "حديقة الملك عبدالله (الملز)", at: [24.6655, 46.7345],
        plants: ["washingtonia", "ficus", "conocarpus", "bougainvillea", "hibiscus", "texas-sage", "duranta", "periwinkle", "thayyil", "clerodendrum", "plumbago", "vitex"] },
      { id: "king-fahd-road", en: "King Fahd Road & Olaya", ar: "طريق الملك فهد والعليا", at: [24.7115, 46.6745],
        plants: ["washingtonia", "date-palm", "conocarpus", "ficus", "texas-sage", "parkinsonia", "lantana", "tecoma", "dodonaea", "clerodendrum", "albizia", "plumbago"] },
      { id: "home-gardens", en: "Home gardens (all over the city)", ar: "حدائق البيوت (في كل الأحياء)", at: [24.775, 46.72],
        plants: ["jasmine", "hibiscus", "desert-rose", "aloe-vera", "mint", "moringa", "bougainvillea", "lemon", "basil", "henna", "grape", "guava", "duranta", "clerodendrum", "plumeria", "rangoon", "plumbago", "ipomoea", "vitex", "shamoum"] },
      { id: "thumamah", en: "Al-Thumamah National Park", ar: "منتزه الثمامة الوطني", at: [25.2, 46.62],
        plants: ["talh", "samur", "sidr", "ghada", "rimth", "harmal", "arfaj", "mesquite", "salam", "sarh", "awsaj", "arta", "nussi", "thumam", "hanzal", "dhanoon", "markh"] },
      { id: "rawdat-khuraim", en: "Rawdat Khuraim", ar: "روضة خريم", at: [25.385, 47.275],
        plants: ["talh", "sidr", "arfaj", "rimth", "harmal", "kaff", "humaidh", "sadan", "qaysoom", "shih", "salam"] },
      { id: "red-sands", en: "Red sand dunes (off the Makkah Road)", ar: "الرمال الحمراء (طريق مكة)", at: [24.49, 46.2],
        plants: ["ghada", "arfaj", "harmal", "rimth", "arta", "nussi", "thumam", "dhanoon", "hanzal", "sadan"] },
      { id: "al-hair", en: "Al-Ha'ir farms (south Riyadh)", ar: "مزارع الحائر (جنوب الرياض)", at: [24.4, 46.83],
        plants: ["date-palm", "lemon", "pomegranate", "fig", "olive", "mint", "moringa", "athel", "alfalfa", "casuarina", "mulberry", "guava", "ushar"] }
    ],

    // Plants that are easy to mix up, with a tip for telling them apart.
    lookalikes: [
      { a: "samur", b: "talh",
        en: "Samur has a flat, umbrella-shaped top and small curly pods. Talh has a rounder, untidy crown, rough dark bark and straight grey pods.",
        ar: "السمر تاجه مسطّح مثل المظلة وقرونه صغيرة ملتفة. أما الطلح فتاجه أكثر استدارة وغير مرتب، ولحاؤه داكن خشن، وقرونه مستقيمة رمادية." },
      { a: "ghada", b: "rimth",
        en: "Ghada is a tall, tree-like shrub (2–5 m) on sand dunes, with thin drooping twigs. Rimth is a low, rounded bush on gravel plains, with short jointed stems.",
        ar: "الغضا شجيرة طويلة تشبه الشجرة (2 إلى 5 أمتار) تنمو على الكثبان الرملية، وأغصانها رفيعة متدلية. أما الرمث فشجيرة قصيرة مستديرة في السهول الحصوية، وسيقانه قصيرة مفصّلة." },
      { a: "date-palm", b: "washingtonia",
        en: "Date palm leaves are feather-shaped and its trunk is rough with old leaf bases. Washingtonia has fan-shaped leaves and a very tall, thin trunk, often with a brown \"skirt\".",
        ar: "سعف النخلة ريشي الشكل وجذعها خشن فيه بقايا الكرب. أما الواشنطونيا فأوراقها على شكل مروحة وجذعها طويل جداً ونحيل، وغالباً عليه \"تنورة\" بنية." },
      { a: "conocarpus", b: "ficus",
        en: "Conocarpus leaves are narrow, pointed and dull, with round button-like fruit. Ficus leaves are shiny and oval, and a broken leaf oozes white sap.",
        ar: "أوراق الكونوكاربس ضيقة ومدببة وغير لامعة، وثماره كروية صغيرة تشبه الأزرار. أما أوراق الفيكس فلامعة وبيضاوية، وإذا قطعت ورقة يخرج منها حليب أبيض." },
      { a: "oleander", b: "desert-rose",
        en: "Oleander is a tall shrub with long, narrow leaves all along its stems. Desert rose is small, with a fat swollen trunk and glossy leaves only at the branch tips.",
        ar: "الدفلة شجيرة طويلة أوراقها طويلة وضيقة على طول السيقان. أما وردة الصحراء فصغيرة، جذعها منتفخ، وأوراقها اللامعة في أطراف الأغصان فقط." },
      { a: "mesquite", b: "parkinsonia",
        en: "Parkinsonia has green bark and long, thin ribbon-like leaves, with yellow flowers marked red. Mesquite has dark bark, feathery leaves, yellow flower spikes and long bean pods.",
        ar: "الباركنسونيا لحاؤها أخضر وأوراقها طويلة رفيعة مثل الشرائط، وأزهارها صفراء فيها بقعة حمراء. أما البرسوبس فلحاؤه داكن وأوراقه ريشية، وأزهاره سنابل صفراء، وقرونه طويلة." },
      { a: "athel", b: "ghada",
        en: "Both look grey-green and needly. Athel is a real tree with tiny scale leaves and pinkish flower spikes, often planted around farms. Ghada is a shrub that grows wild on sand dunes.",
        ar: "الاثنان لونهما أخضر رمادي ويبدوان إبريين. الأثل شجرة حقيقية أوراقها حراشف صغيرة وأزهاره سنابل وردية، ويُزرع غالباً حول المزارع. أما الغضا فشجيرة برية تنمو على الكثبان الرملية." },
      { a: "shih", b: "qaysoom",
        en: "Both are grey, scented desert shrubs. Shih has tiny, finely cut leaves and a bitter smell. Qaysoom is woollier and has round yellow button flowers and a camphor smell.",
        ar: "الاثنان شجيرتان رماديتان عطريتان. الشيح أوراقه صغيرة جداً ومقسّمة ورائحته مرّة. أما القيصوم فأكثر صوفية، وأزهاره صفراء مستديرة مثل الأزرار، ورائحته تشبه الكافور." },
      { a: "salam", b: "samur",
        en: "Salam is a smaller, bushier acacia with yellow ball flowers. Samur is a bigger tree with a flat umbrella top, white-cream flowers and curly pods.",
        ar: "السلم أكاسيا أصغر وأكثر كثافة وأزهاره صفراء كروية. أما السمر فشجرة أكبر تاجها مسطح مثل المظلة، وأزهاره بيضاء كريمية، وقرونه ملتفة." },
      { a: "arta", b: "ghada",
        en: "Both grow on sand dunes with thin green twigs. Arta has jointed twigs and round, bristly fruit. Ghada is taller and tree-like, with winged papery fruit.",
        ar: "الاثنان ينموان على الكثبان الرملية وأغصانهما خضراء رفيعة. الأرطى أغصانه مفصّلة وثمرته مستديرة كثيرة الشعيرات. أما الغضا فأطول ويشبه الشجرة، وثمره ورقي مجنّح." },
      { a: "casuarina", b: "athel",
        en: "Both look needly and are used as windbreaks. Casuarina is a tall, straight tree with small woody cones. Athel is grey-green, often wider than tall, with pink flower spikes and no cones.",
        ar: "الاثنان يبدوان إبريين ويُستخدمان مصدات للرياح. الكازورينا شجرة طويلة مستقيمة لها مخاريط خشبية صغيرة. أما الأثل فلونه أخضر رمادي، وغالباً عرضه أكبر من طوله، وأزهاره سنابل وردية بلا مخاريط." },
      { a: "clerodendrum", b: "ficus",
        en: "Both are shiny green hedges. Clerodendrum leaves grow in opposite pairs and it has white flowers with purple whiskers. Ficus leaves alternate, and a broken leaf oozes white sap.",
        ar: "الاثنان سياج أخضر لامع. أوراق الكلروديندرم متقابلة في أزواج، وأزهاره بيضاء بشوارب بنفسجية. أما أوراق الفيكس فمتبادلة، وإذا قطعت ورقة يخرج منها حليب أبيض." },
      { a: "hanzal", b: "ushar",
        en: "Both have round green fruit you'll see in the desert. Hanzal is a creeping vine with striped, solid fruit. Ushar is an upright shrub with big grey leaves and hollow, balloon-like fruit.",
        ar: "الاثنان لهما ثمار خضراء مستديرة تراها في البر. الحنظل نبات زاحف ثمرته مخططة ومصمتة. أما العشار فشجيرة قائمة أوراقها كبيرة رمادية، وثمرته مجوّفة مثل البالون." },
      { a: "jasmine", b: "plumeria",
        en: "Fulla jazani is a small shrub with small white flowers and no milky sap. Indian jasmine is a small tree with thick branches, big oval leaves, big white flowers with a yellow centre, and white milky sap.",
        ar: "الفل الجازاني شجيرة صغيرة أزهارها بيضاء صغيرة وليس فيها حليب. أما الياسمين الهندي فشجرة صغيرة أغصانها سميكة وأوراقها بيضاوية كبيرة، وأزهارها بيضاء كبيرة وسطها أصفر، وفيها حليب أبيض." },
      { a: "rangoon", b: "bougainvillea",
        en: "Both are red-pink climbers on walls. Red climbing jasmine has real tube flowers that change from white to red and smell sweet. Bougainvillea's colour comes from papery bracts and it has no scent.",
        ar: "الاثنان متسلقان ولونهما أحمر وردي على الأسوار. الياسمين الأحمر المتسلق أزهاره حقيقية أنبوبية تتغير من الأبيض إلى الأحمر ورائحتها حلوة. أما الجهنمية فلونها من قنابات ورقية وليس لها رائحة." },
      { a: "plumbago", b: "duranta",
        en: "Both have blue-violet flowers. Blue jasmine has round clusters of pale sky-blue flowers at the tips. Duranta has hanging chains of violet flowers followed by golden berries.",
        ar: "الاثنان أزهارهما زرقاء بنفسجية. الياسمين الأزرق عناقيده مستديرة بلون أزرق سماوي فاتح في أطراف الأغصان. أما الدورانتا فعناقيدها متدلية بنفسجية وتتبعها ثمار ذهبية." },
      { a: "vitex", b: "kaff",
        en: "Both are called kaff maryam. The tree (Vitex) has hand-shaped leaves and purple flower spikes. The desert one (Anastatica) is a tiny grey herb that dries into a ball and opens in water.",
        ar: "الاثنان يسميان كف مريم. الشجرة (فيتكس) أوراقها مثل الكف وأزهارها سنابل بنفسجية. أما الصحراوية (أناستاتيكا) فعشبة رمادية صغيرة تجف وتلتف مثل الكرة وتنفتح في الماء." },
      { a: "shamoum", b: "basil",
        en: "Shamoum (local basil) has tall purple flower spikes, often purplish stems, and a strong scent. Italian basil has big, soft, shiny leaves, small white flowers, and a milder, sweet smell; it's the one used in cooking.",
        ar: "الشموم (الريحان البلدي) شماريخه الزهرية بنفسجية طويلة وسيقانه غالباً مائلة للبنفسجي ورائحته قوية. أما الريحان الإيطالي فأوراقه كبيرة طرية لامعة وأزهاره بيضاء صغيرة ورائحته أخف وأحلى، وهو الذي يُستخدم في الطبخ." }
    ]
  }
};

// Shortcuts used in each plant's native range. "@NAME" expands to these countries.
window.REGIONS = {
  ARABIA: ["Saudi Arabia", "Yemen", "Oman", "United Arab Emirates", "Qatar", "Kuwait"],
  LEVANT: ["Jordan", "Israel", "Palestine", "Lebanon", "Syria"],
  NAFRICA: ["Egypt", "Libya", "Tunisia", "Algeria", "Morocco", "W. Sahara"],
  EAFRICA: ["Sudan", "S. Sudan", "Eritrea", "Ethiopia", "Djibouti", "Somalia", "Somaliland", "Kenya", "Uganda", "Tanzania"],
  SAFRICA: ["Mozambique", "Malawi", "Zambia", "Zimbabwe", "Botswana", "Namibia", "South Africa", "eSwatini", "Lesotho", "Angola"],
  CASIA: ["Kazakhstan", "Uzbekistan", "Turkmenistan", "Tajikistan", "Kyrgyzstan", "Afghanistan"],
  CAMERICA: ["Mexico", "Guatemala", "Belize", "Honduras", "El Salvador", "Nicaragua", "Costa Rica", "Panama"],
  NSAMERICA: ["Colombia", "Venezuela", "Ecuador", "Peru", "Guyana", "Suriname"]
};
