#!/usr/bin/env python3
"""Download plant photos from Wikimedia Commons, resize to 800px wide,
and regenerate js/credits.js + CREDITS.md.

Usage: python3 tools/fetch_photos.py            # all plants in tools/photos.json
       python3 tools/fetch_photos.py sidr fig   # only these ids

tools/photos.json maps plant id -> Commons file name (without "File:").
Requires Pillow (pip install pillow).
"""
import html, io, json, os, re, sys, time, urllib.parse, urllib.request
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UA = "RiyadhPlantsApp/1.0 (https://github.com/sha3abdullah/riyadh-plants-app) python-urllib"
API = "https://commons.wikimedia.org/w/api.php"
WIDTH = 800

# Some Commons "Artist" fields hold a paragraph of text; use a short name instead.
AUTHOR_FIX = {
    "Fruit_of_Conocarpus_lancifolius.jpg": "Matthew Smith",
}


def get(url, tries=10):
    delay = 2
    for _ in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=90) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 502, 503, 504):
                time.sleep(delay)
                delay = min(delay * 2, 60)
                continue
            raise RuntimeError(f"HTTP {e.code} for {url}")
        except urllib.error.URLError as e:
            raise RuntimeError(f"Blocked or unreachable: {urllib.parse.urlparse(url).netloc} ({e.reason})")
    raise RuntimeError(f"Gave up after rate limiting: {url}")


def strip_tags(s):
    return html.unescape(re.sub(r"<[^>]+>", "", s or "")).strip()


def info(files):
    q = urllib.parse.urlencode({
        "action": "query", "format": "json", "prop": "imageinfo",
        "iiprop": "url|extmetadata", "iiurlwidth": 960,
        "titles": "|".join("File:" + f for f in files),
    })
    j = json.loads(get(API + "?" + q))
    norm = {n["to"]: n["from"] for n in j["query"].get("normalized", [])}
    out = {}
    for p in j["query"]["pages"].values():
        if "imageinfo" not in p:
            raise RuntimeError(f"Missing file on Commons: {p['title']}")
        name = norm.get(p["title"], p["title"])[5:]
        out[name] = p["imageinfo"][0]
    return out


def main():
    photos = json.load(open(os.path.join(ROOT, "tools", "photos.json")))
    only = sys.argv[1:]
    credits_path = os.path.join(ROOT, "tools", "credits.json")
    credits = json.load(open(credits_path)) if os.path.exists(credits_path) else {}
    ids = [i for i in photos if not only or i in only]
    for k in range(0, len(ids), 20):
        chunk = ids[k:k + 20]
        meta = info([photos[i] for i in chunk])
        for pid in chunk:
            f = photos[pid]
            ii = meta[f]
            em = ii.get("extmetadata", {})
            src = ii.get("thumburl") or ii["url"]
            img = Image.open(io.BytesIO(get(src))).convert("RGB")
            if img.width > WIDTH:
                img = img.resize((WIDTH, round(img.height * WIDTH / img.width)), Image.LANCZOS)
            img.save(os.path.join(ROOT, "images", pid + ".jpg"), "JPEG", quality=82, optimize=True, progressive=True)
            credits[pid] = {
                "file": f,
                "author": AUTHOR_FIX.get(f) or strip_tags(em.get("Artist", {}).get("value")) or "Unknown",
                "license": strip_tags(em.get("LicenseShortName", {}).get("value")) or "See source",
                "licenseUrl": em.get("LicenseUrl", {}).get("value", ""),
                "source": ii["descriptionurl"],
            }
            print(f"ok  {pid:14} {img.width}x{img.height}  {credits[pid]['license']}  {f}")
            time.sleep(1)
    credits = {i: credits[i] for i in photos if i in credits}
    json.dump(credits, open(credits_path, "w"), indent=1, ensure_ascii=False)
    with open(os.path.join(ROOT, "js", "credits.js"), "w") as fh:
        fh.write("/* Generated by tools/fetch_photos.py. Do not edit by hand. */\n")
        fh.write("window.PHOTO_CREDITS = " + json.dumps(credits, indent=1, ensure_ascii=False) + ";\n")
    with open(os.path.join(ROOT, "CREDITS.md"), "w") as fh:
        fh.write("# Photo credits\n\nAll plant photos come from [Wikimedia Commons](https://commons.wikimedia.org) "
                 "under free licenses. They were resized to 800px wide. Nothing else was changed.\n\n"
                 "| Plant | Photo | Author | License |\n|---|---|---|---|\n")
        for pid, c in credits.items():
            lic = f"[{c['license']}]({c['licenseUrl']})" if c["licenseUrl"] else c["license"]
            author = c["author"].replace("|", "/").replace("\n", " ")
            fh.write(f"| {pid} | [{c['file']}]({c['source']}) | {author} | {lic} |\n")


if __name__ == "__main__":
    main()
