#!/usr/bin/env node
// Builds js/world.js: a tiny offline world map (one SVG path per country)
// for the "Where it comes from" mini-map.
// Usage: node tools/make_world.js <path to world-atlas/countries-110m.json> <path to topojson-client>
const fs = require("fs");
const path = require("path");
const [atlasPath, topoPath] = process.argv.slice(2);
const topojson = require(path.resolve(topoPath));
const world = JSON.parse(fs.readFileSync(atlasPath, "utf8"));
const geo = topojson.feature(world, world.objects.countries);

const S = 2, TOP = 84, BOTTOM = -58; // crop polar areas
const W = 360 * S, H = (TOP - BOTTOM) * S;
const px = (lon, lat) => [Math.round((lon + 180) * S * 10) / 10, Math.round((TOP - lat) * S * 10) / 10];

function ring(r) {
  return "M" + r.map(([lo, la]) => px(lo, la).join(",")).join("L") + "Z";
}
const out = {};
for (const f of geo.features) {
  const name = f.properties.name;
  if (name === "Antarctica") continue;
  const g = f.geometry;
  if (!g) continue;
  const polys = g.type === "Polygon" ? [g.coordinates] : g.coordinates;
  out[name] = (out[name] || "") + polys.map((p) => p.map(ring).join("")).join("");
}
const js = "/* Generated by tools/make_world.js from Natural Earth (public domain) via world-atlas. */\n" +
  "window.WORLD = " + JSON.stringify({ w: W, h: H, s: S, top: TOP, countries: out }) + ";\n";
fs.writeFileSync(path.join(__dirname, "..", "js", "world.js"), js);
console.log(Object.keys(out).length, "countries,", (js.length / 1024).toFixed(0), "KB");
console.log(Object.keys(out).sort().join(" | "));
